# Generated by Django 3.2.5 on 2021-07-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_music_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.music')),
            ],
        ),
    ]
