# Generated by Django 3.2.5 on 2021-07-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='listening date')),
                ('listened', models.CharField(choices=[('C', 'Casette'), ('D', 'CD'), ('L', 'Live'), ('P', 'Pandora'), ('R', 'Radio'), ('S', 'Spotify')], default='C', max_length=1)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.music')),
            ],
        ),
    ]
