# Generated by Django 3.2.5 on 2021-07-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_listened_listen_listening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['-date']},
        ),
    ]
