# Generated by Django 3.2.5 on 2021-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_music_spotify_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='type',
            field=models.CharField(choices=[('A', 'Artist'), ('B', 'Album'), ('T', 'Track')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='music',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
