# Generated by Django 3.2.5 on 2021-07-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210729_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='spotify_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
